services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  backend:
    build: ./backend
    dns:
      - 8.8.8.8
    depends_on:
      - mongodb  
    ports:
      - "5000:5000"
    networks:
    - mynetwork  
    environment:
      - MONGO_URI=mongodb+srv://maazabdulbasith:AbdulBasithMaaz%402826@administrator.nb6ouiq.mongodb.net/Administrator
      - NODE_ENV=production
      - PORT=5000
    restart: always

  frontend:
    build: ./frontend/react-admin
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: always

volumes:
  mongo-data:
